# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-extension:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - uses: er28-0652/setup-ghidra@master
      with:
        version: "11.2"

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '8.5'

    - name: Build with Gradle Wrapper
      run: gradle buildExtension
      working-directory: ./GhidraR2Web

    - name: Release 
      uses: softprops/action-gh-release@v1
      with:
        files: |
          GhidraR2Web/dist/*.zip
          GhidraR2WebServer.java
          r2g
          README.md
        name: ghidra-r2web_${{GITHUB_SHA}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


